Localization:
  dxgettext:
    .Path: C:\Program Files (x86)\dxgettext
    URL: http://dxgettext.po.dk/
  Yaml:
    DefaultKeyNames:
      Key: AppTitle
      Key: ConfirmationMessage
      Key: DisplayLabel
      Key: Folder
      Key: FreeSearch
      Key: Hint
      Key: PluralDisplayLabel
