AppTitle: {AppTitle}

Databases:

Auth: Null

AccessControl: Null

ExtJS:
  Theme: classic
  AjaxTimeout: 100000

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

Server:
  Port: 8080
  ThreadPoolSize: 20
  # In minutes.
  SessionTimeOut: 10
