AppTitle: _(Peoria Girls and their Dolls)

Databases:
  # Switch Main and Other to switch databases.

  Main: DBX
    Connection:
      DriverName: Firebird
      DataBase: localhost:HelloKitto
      User_Name: SYSDBA
      Password: masterkey
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

  Other: DBX
    Connection:
      DriverName: MSSQL
      HostName: localhost
      DataBase: HelloKitto
      OS Authentication: True

  NotWorking: ADO
    Connection:
      # This doesn't work because of a bug with date and time fields in ADO/OLEDB.
      # See http://qc.embarcadero.com/wc/qcmain.aspx?d=78910
      ConnectionString: Provider=SQLOLEDB.1;User ID=sa;Password=;Initial Catalog=HelloKitto;Data Source=%COMPUTERNAME%
      # Using the Native client fixes the date bug but still not the time bug.
      ConnectionString: >
        Provider=SQLNCLI10;
        User ID=sa;
        Password=;
        Initial Catalog=HelloKitto;
        Data Source=localhost;
        Use Procedure for Prepare=1;
        Auto Translate=True;
        Packet Size=4096;

Auth: DB
  Defaults:
    UserName: cwolter
    Password: cwolter

AccessControl: Null
    
# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

Ext:
  Theme: blue
  URL: /ext

LanguageId: it
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8
