IsClearPassword:
IsPassepartoutEnabled:
Defaults:
PassepartoutPassword:
ReadUserCommandText:
ReadUserCommandText:
SetPasswordCommandText:
SetPasswordCommandText:
AfterAuthenticateCommandText:
FileName:
