ADODatabase: ADO
  CheckValue: True
  Template:
    Connection:
      Provider: SQLNCLI10
      Trusted_Connection: Yes
      Initial Catalog: ChangeMe
      Data Source: %COMPUTERNAME%
DBXDatabase: DBX
  CheckValue: True
  Template:
    Connection:
      DriverName: Firebird
      DataBase: localhost:ChangeMe
      User_Name: SYSDBA
      Password: masterkey
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False  
FDDatabase: FD
  CheckValue: True
  Template:
    Connection:
      # Example for Firebird using FireDAC
      DriverID: FB
      # Alias of database defined in Aliases.conf or filename
      Database: ChangeMe
      User_Name: ChangeMe
      Password: ChangeMe
      Server: localhost
      CharacterSet: UTF8
      Protocol: TCPIP
      Isolation: ReadCommitted