AppTitle: New project

Databases:
  # The 'Main' database is used by default. Change settings below accordingly.
  
  Main: DBX
    Connection:
      DriverName: Firebird
      DataBase: localhost:ChangeMe
      User_Name: SYSDBA
      Password: masterkey
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

  MSSQL_DBX_Example: DBX
    Connection:
      DriverName: MSSQL
      HostName: localhost
      DataBase: ChangeMe
      OS Authentication: True

  MSSQL_ADO_Example: ADO
    Connection:
      # Currently you can't use ADO if you use date and time fields.
      # See http://qc.embarcadero.com/wc/qcmain.aspx?d=78910
      ConnectionString: Provider=SQLOLEDB.1;User ID=sa;Password=;Initial Catalog=ChangeMe;Data Source=%COMPUTERNAME%
      # Using the Native client fixes the date bug but still not the time bug.
      ConnectionString: >
        Provider=SQLNCLI10;
        User ID=sa;
        Password=;
        Initial Catalog=ChangeMe;
        Data Source=localhost;
        Use Procedure for Prepare=1;
        Auto Translate=True;
        Packet Size=4096;

Auth: DB
  Defaults:
    UserName:
    Password:

AccessControl: Null
    
# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

Ext:
  Theme: blue
  URL: /ext

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8
