AppName: DbDemos2
AppTitle: Biolife
AppIcon: DbDemosIcon
# Default is the application name in lower case.
AppPath: /dbdemos
Application:
  # When using partial proxy mode (serving /hellokitto/res/ from a separate web server)
  # you can set this to False to gain some speed. Default is True.
  #HandleResources: False

Databases:
  Main: FD
    Connection:
      # Example for FireDAC
      DriverID: IB
      Database: D:\Users\Public\Documents\Embarcadero\Studio\19.0\Samples\Data\dbdemos.gdb
      User_Name: SYSDBA
      Password: masterkey
      Protocol: TCPIP
      Server: localhost
      CharacterSet: UTF8
      Isolation: ReadCommitted

AccessControl: Null

ExtJS:
  Theme: crisp
  AjaxTimeout: 100000

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

Server:
  Port: 2604
  ThreadPoolSize: 20
  # In minutes.
  SessionTimeOut: 10
