AppTitle: Tasks & Activities

LoginWindowAppearance:
  HtmlPanel: |
    <center>
      <p><img src="%IMAGE(taskitto_logo_150)%"></img></p>
      <p>An example activity tracking application.</p>
    </center>
  HtmlPanelWidth: 300
  HtmlPanelHeight: 80

Databases:
  Main: DBX
    Connection:
      DriverName: Firebird
      DataBase: localhost:TASKITTO
      User_Name: SYSDBA
      Password: masterkey
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

Auth: DB
  IsClearPassword: True
  Defaults:
    .UserName: admin
    .Password: admin

AccessControl: Null

# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

Ext:
  Theme: gray

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

FOPEnginePath: %FOP1_1%

FastCGI:
  TCPPort: 2202

UserFormats:
  Date: dd/mm/yyyy
  Time: hh:nn
